### ISSUE TITLE
OS Support

### ISSUE THREAD

**Issue by chintanp** [apsavin/pgrights#16]
What OSes does this software support currently? Some details about this in the README would be appreciated.

**Comment by apsavin** [comment]
It's based on Electron, so I expect it to work everywhere. But I tested it only on MacOS, so I prebuild dmg files only. And yes, I think I'll add this information to the README.

**Comment by chintanp** [comment]
On my WSL 2 in Windows 10, I get the error below when I try the build instructions: 

![image](https://user-images.githubusercontent.com/752869/107129235-d727b500-6878-11eb-97f5-376bdbb45cdc.png)

I have never used `yarn` before, so I could be making a very obvious mistake.

**Comment by apsavin** [comment]
@chintanp Please try to use [this instruction](https://github.com/yarnpkg/yarn/issues/2821#issuecomment-284181365)

**Comment by chintanp** [comment]
@apsavin thanks for the link. Should have googled before posting. I tried the above and got yarn installed and working (i.e. it is doing its nodejs things). However, then stuck on the error below: 

```
yarn && yarn package
yarn install v1.22.5
[1/4] Resolving packages...
success Already up-to-date.
$ electron-builder install-app-deps
  • electron-builder  version=22.9.1
  • loaded configuration  file=package.json ("build" field)
  • rebuilding native dependencies  dependencies=keytar@4.13.0 platform=linux arch=x64
  • install prebuilt binary  name=keytar version=4.13.0 platform=linux arch=x64
  • build native dependency from sources  name=keytar
                                          version=4.13.0
                                          platform=linux
                                          arch=x64
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=prebuild-install info begin Prebuild-install version 5.3.0
    prebuild-install info looking for cached prebuild @ /root/.npm/_prebuilds/1d9a41-keytar-v4.13.0-electron-v75-linux-x64.tar.gz
    prebuild-install http request GET https://github.com/atom/node-keytar/releases/download/v4.13.0/keytar-v4.13.0-electron-v75-linux-x64.tar.gz
    prebuild-install http 404 https://github.com/atom/node-keytar/releases/download/v4.13.0/keytar-v4.13.0-electron-v75-linux-x64.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=7.3.3 runtime=electron arch=x64 libc= platform=linux)

  • rebuilding native dependency  name=keytar version=4.13.0
Done in 8.35s.
yarn run v1.22.5
$ yarn build && electron-builder build --publish never
$ concurrently "yarn build-main" "yarn build-renderer"
$ cross-env NODE_ENV=production webpack --config ./configs/webpack.config.renderer.prod.babel.js --colors
$ cross-env NODE_ENV=production webpack --config ./configs/webpack.config.main.prod.babel.js --colors
[0] /mnt/d/temp/electronapps/pgrights/node_modules/webpack-cli/bin/cli.js:281
[0]                             throw err;
[0]                             ^
[0]
[0] Error: Cannot find module 'vs/editor/contrib/gotoSymbol/goToCommands'
[0] Require stack:
[0] - /mnt/d/temp/electronapps/pgrights/node_modules/monaco-editor-webpack-plugin/out/index.js
[0] - /mnt/d/temp/electronapps/pgrights/configs/webpack.config.base.js
[0] - /mnt/d/temp/electronapps/pgrights/configs/webpack.config.main.prod.babel.js
[0] - /mnt/d/temp/electronapps/pgrights/node_modules/webpack-cli/bin/utils/convert-argv.js
[0] - /mnt/d/temp/electronapps/pgrights/node_modules/webpack-cli/bin/cli.js
[0] - /mnt/d/temp/electronapps/pgrights/node_modules/webpack/bin/webpack.js
[0]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
[0]     at Function.resolve (/mnt/d/temp/electronapps/pgrights/node_modules/v8-compile-cache/v8-compile-cache.js:164:23)
[0]     at resolveMonacoPath (/mnt/d/temp/electronapps/pgrights/node_modules/monaco-editor-webpack-plugin/out/index.js:34:28)
[0]     at /mnt/d/temp/electronapps/pgrights/node_modules/monaco-editor-webpack-plugin/out/index.js:173:63
[0]     at Array.map (<anonymous>)
[0]     at createLoaderRules (/mnt/d/temp/electronapps/pgrights/node_modules/monaco-editor-webpack-plugin/out/index.js:173:43)
[0]     at MonacoEditorWebpackPlugin.apply (/mnt/d/temp/electronapps/pgrights/node_modules/monaco-editor-webpack-plugin/out/index.js:91:23)
[0]     at webpack (/mnt/d/temp/electronapps/pgrights/node_modules/webpack/lib/webpack.js:51:13)
[0]     at processOptions (/mnt/d/temp/electronapps/pgrights/node_modules/webpack-cli/bin/cli.js:272:16)
[0]     at /mnt/d/temp/electronapps/pgrights/node_modules/webpack-cli/bin/cli.js:364:3
[0]     at Object.parse (/mnt/d/temp/electronapps/pgrights/node_modules/webpack-cli/node_modules/yargs/yargs.js:576:18)
[0]     at /mnt/d/temp/electronapps/pgrights/node_modules/webpack-cli/bin/cli.js:49:8
[0]     at Object.<anonymous> (/mnt/d/temp/electronapps/pgrights/node_modules/webpack-cli/bin/cli.js:366:3)
[0]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[0]     at Module.load (internal/modules/cjs/loader.js:928:32)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[0]     at Module.require (internal/modules/cjs/loader.js:952:19)
[0]     at require (internal/modules/cjs/helpers.js:88:18)
[0]     at Object.<anonymous> (/mnt/d/temp/electronapps/pgrights/node_modules/webpack/bin/webpack.js:156:2)
[0]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[0]     at Module.load (internal/modules/cjs/loader.js:928:32)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[0]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
[0]     at internal/main/run_main_module.js:17:47 {
[0]   code: 'MODULE_NOT_FOUND',
[0]   requireStack: [
[0]     '/mnt/d/temp/electronapps/pgrights/node_modules/monaco-editor-webpack-plugin/out/index.js',
[0]     '/mnt/d/temp/electronapps/pgrights/configs/webpack.config.base.js',
[0]     '/mnt/d/temp/electronapps/pgrights/configs/webpack.config.main.prod.babel.js',
[0]     '/mnt/d/temp/electronapps/pgrights/node_modules/webpack-cli/bin/utils/convert-argv.js',
[0]     '/mnt/d/temp/electronapps/pgrights/node_modules/webpack-cli/bin/cli.js',
[0]     '/mnt/d/temp/electronapps/pgrights/node_modules/webpack/bin/webpack.js'
[0]   ]
[0] }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[0] yarn build-main exited with code 1
[1] /mnt/d/temp/electronapps/pgrights/node_modules/webpack-cli/bin/cli.js:281
[1]                             throw err;
[1]                             ^
[1]
[1] Error: Cannot find module 'vs/editor/contrib/gotoSymbol/goToCommands'
[1] Require stack:
[1] - /mnt/d/temp/electronapps/pgrights/node_modules/monaco-editor-webpack-plugin/out/index.js
[1] - /mnt/d/temp/electronapps/pgrights/configs/webpack.config.base.js
[1] - /mnt/d/temp/electronapps/pgrights/configs/webpack.config.renderer.prod.babel.js
[1] - /mnt/d/temp/electronapps/pgrights/node_modules/webpack-cli/bin/utils/convert-argv.js
[1] - /mnt/d/temp/electronapps/pgrights/node_modules/webpack-cli/bin/cli.js
[1] - /mnt/d/temp/electronapps/pgrights/node_modules/webpack/bin/webpack.js
[1]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
[1]     at Function.resolve (/mnt/d/temp/electronapps/pgrights/node_modules/v8-compile-cache/v8-compile-cache.js:164:23)
[1]     at resolveMonacoPath (/mnt/d/temp/electronapps/pgrights/node_modules/monaco-editor-webpack-plugin/out/index.js:34:28)
[1]     at /mnt/d/temp/electronapps/pgrights/node_modules/monaco-editor-webpack-plugin/out/index.js:173:63
[1]     at Array.map (<anonymous>)
[1]     at createLoaderRules (/mnt/d/temp/electronapps/pgrights/node_modules/monaco-editor-webpack-plugin/out/index.js:173:43)
[1]     at MonacoEditorWebpackPlugin.apply (/mnt/d/temp/electronapps/pgrights/node_modules/monaco-editor-webpack-plugin/out/index.js:91:23)
[1]     at webpack (/mnt/d/temp/electronapps/pgrights/node_modules/webpack/lib/webpack.js:51:13)
[1]     at processOptions (/mnt/d/temp/electronapps/pgrights/node_modules/webpack-cli/bin/cli.js:272:16)
[1]     at /mnt/d/temp/electronapps/pgrights/node_modules/webpack-cli/bin/cli.js:364:3
[1]     at Object.parse (/mnt/d/temp/electronapps/pgrights/node_modules/webpack-cli/node_modules/yargs/yargs.js:576:18)
[1]     at /mnt/d/temp/electronapps/pgrights/node_modules/webpack-cli/bin/cli.js:49:8
[1]     at Object.<anonymous> (/mnt/d/temp/electronapps/pgrights/node_modules/webpack-cli/bin/cli.js:366:3)
[1]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[1]     at Module.load (internal/modules/cjs/loader.js:928:32)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[1]     at Module.require (internal/modules/cjs/loader.js:952:19)
[1]     at require (internal/modules/cjs/helpers.js:88:18)
[1]     at Object.<anonymous> (/mnt/d/temp/electronapps/pgrights/node_modules/webpack/bin/webpack.js:156:2)
[1]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[1]     at Module.load (internal/modules/cjs/loader.js:928:32)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[1]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
[1]     at internal/main/run_main_module.js:17:47 {
[1]   code: 'MODULE_NOT_FOUND',
[1]   requireStack: [
[1]     '/mnt/d/temp/electronapps/pgrights/node_modules/monaco-editor-webpack-plugin/out/index.js',
[1]     '/mnt/d/temp/electronapps/pgrights/configs/webpack.config.base.js',
[1]     '/mnt/d/temp/electronapps/pgrights/configs/webpack.config.renderer.prod.babel.js',
[1]     '/mnt/d/temp/electronapps/pgrights/node_modules/webpack-cli/bin/utils/convert-argv.js',
[1]     '/mnt/d/temp/electronapps/pgrights/node_modules/webpack-cli/bin/cli.js',
[1]     '/mnt/d/temp/electronapps/pgrights/node_modules/webpack/bin/webpack.js'
[1]   ]
[1] }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[1] yarn build-renderer exited with code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
Initial research on Google did not help much with this.
